log:
  loglevel: warning
dns:
  servers:
  - https+local://dns.google/dns-query
  - 1.1.1.1
inbounds:
- port: 8080
  protocol: trojan
  settings:
    clients:
    - password: "fd53689b-c4ec-491d-9dbf-12c28a3cfadd"
  streamSettings:
    network: ws
    wsSettings:
      path: /bfd53689b-c4ec-491d-9dbf-12c28a3cfadd/
  sniffing:
    enabled: true
    destOverride:
    - http
    - tls
    - quic
outbounds:
- protocol: freedom
  tag: direct
  settings:
    domainStrategy: UseIPv4
